export const initialMockData = [
    {
        "PNS ID": "A827391823901",
        "NIP BARU": "199405122021071002",
        "NIP LAMA": "-",
        "NAMA": "ARIEF SETIAWAN",
        "GELAR DEPAN": "S.Kom.",
        "GELAR BELAKANG": "M.T.",
        "TEMPAT LAHIR ID": "3171",
        "TEMPAT LAHIR NAMA": "JAKARTA PUSAT",
        "TANGGAL LAHIR": "1994-05-12",
        "JENIS KELAMIN": "L",
        "AGAMA ID": "1",
        "AGAMA NAMA": "ISLAM",
        "JENIS KAWIN ID": "1",
        "JENIS KAWIN NAMA": "KAWIN",
        "NIK": "3171021205940003",
        "NOMOR HP": "081234567890",
        "EMAIL": "arief.setiawan@gmail.com",
        "EMAIL GOV": "arief.setiawan@jakarta.go.id",
        "ALAMAT": "Jl. Merdeka Barat No. 15, Gambir, Jakarta Pusat",
        "NPWP NOMOR": "48.123.456.7-012.000",
        "BPJS": "0001234567890",
        "JENIS PEGAWAI ID": "2",
        "JENIS PEGAWAI NAMA": "PPPK",
        "KEDUDUKAN HUKUM ID": "1",
        "KEDUDUKAN HUKUM NAMA": "AKTIF",
        "STATUS CPNS PNS": "PPPK",
        "KARTU ASN VIRTUAL": "ASN-V-19940512",
        "NOMOR SK CPNS": "800/102/PPPK/2021",
        "TANGGAL SK CPNS": "2021-07-01",
        "TMT CPNS": "2021-07-15", // This makes contract end in July 2026 (soon!)
        "NOMOR SK PNS": "-",
        "TANGGAL SK PNS": "-",
        "TMT PNS": "-",
        "GOL AWAL ID": "IX",
        "GOL AWAL NAMA": "Golongan IX",
        "GOL AKHIR ID": "IX",
        "GOL AKHIR NAMA": "Golongan IX",
        "TMT GOLONGAN": "2021-07-15",
        "MK TAHUN": 5,
        "MK BULAN": 0,
        "JENIS JABATAN ID": "2",
        "JENIS JABATAN NAMA": "FUNGSIONAL",
        "JABATAN ID": "J0192",
        "JABATAN NAMA": "PRANATA KOMPUTER AHLI PERTAMA",
        "TMT JABATAN": "2021-07-15",
        "TINGKAT PENDIDIKAN ID": "S2",
        "TINGKAT PENDIDIKAN NAMA": "PASCA SARJANA",
        "PENDIDIKAN ID": "P1029",
        "PENDIDIKAN NAMA": "TEKNOLOGI INFORMASI",
        "TAHUN LULUS": 2018,
        "KPKN ID": "K012",
        "KPKN NAMA": "KPKN JAKARTA I",
        "LOKASI KERJA ID": "L3171",
        "LOKASI KERJA NAMA": "BALAI KOTA DKI JAKARTA",
        "UNOR ID": "U9810",
        "UNOR NAMA": "DINAS KOMUNIKASI, INFORMATIKA DAN STATISTIK - BAGIAN PENGEMBANGAN SISTEM INFORMASI",
        "INSTANSI INDUK ID": "I3100",
        "INSTANSI INDUK NAMA": "PEMERINTAH PROVINSI DKI JAKARTA",
        "INSTANSI KERJA ID": "I3100",
        "INSTANSI KERJA NAMA": "PEMERINTAH PROVINSI DKI JAKARTA",
        "SATUAN KERJA INDUK ID": "S091",
        "SATUAN KERJA INDUK NAMA": "SEKRETARIAT DAERAH",
        "SATUAN KERJA KERJA ID": "S095",
        "SATUAN KERJA KERJA NAMA": "BAGIAN PENGEMBANGAN SISTEM INFORMASI",
        "IS VALID NIK": "YA",
        "NAMA SEKOLAH": "UNIVERSITAS INDONESIA",
        "FLAG IKD": "1",
        "GAJI": "",
        "NOMOR_KONTRAK": "SPK/9801/DISKOMINFO/2021",
        "STATUS_PERPANJANGAN": "Belum Diproses"
    },
    {
        "PNS ID": "A827391823902",
        "NIP BARU": "199108242021081001",
        "NIP LAMA": "-",
        "NAMA": "DIAN PRATIWI",
        "GELAR DEPAN": "Dr.",
        "GELAR BELAKANG": "S.H., M.H.",
        "TEMPAT LAHIR ID": "3578",
        "TEMPAT LAHIR NAMA": "SURABAYA",
        "TANGGAL LAHIR": "1991-08-24",
        "JENIS KELAMIN": "P",
        "AGAMA ID": "1",
        "AGAMA NAMA": "ISLAM",
        "JENIS KAWIN ID": "1",
        "JENIS KAWIN NAMA": "KAWIN",
        "NIK": "3578022408910005",
        "NOMOR HP": "081299998888",
        "EMAIL": "dian.pratiwi@gmail.com",
        "EMAIL GOV": "dian.pratiwi@surabaya.go.id",
        "ALAMAT": "Jl. Dharmahusada Indah No. 45, Surabaya",
        "NPWP NOMOR": "48.987.654.3-012.000",
        "BPJS": "0005432109876",
        "JENIS PEGAWAI ID": "2",
        "JENIS PEGAWAI NAMA": "PPPK",
        "KEDUDUKAN HUKUM ID": "1",
        "KEDUDUKAN HUKUM NAMA": "AKTIF",
        "STATUS CPNS PNS": "PPPK",
        "KARTU ASN VIRTUAL": "ASN-V-19910824",
        "NOMOR SK CPNS": "800/215/PPPK/2021",
        "TANGGAL SK CPNS": "2021-08-01",
        "TMT CPNS": "2021-08-15", // Contract end August 2026 (soon!)
        "NOMOR SK PNS": "-",
        "TANGGAL SK PNS": "-",
        "TMT PNS": "-",
        "GOL AWAL ID": "X",
        "GOL AWAL NAMA": "Golongan X",
        "GOL AKHIR ID": "X",
        "GOL AKHIR NAMA": "Golongan X",
        "TMT GOLONGAN": "2021-08-15",
        "MK TAHUN": 5,
        "MK BULAN": 0,
        "JENIS JABATAN ID": "2",
        "JENIS JABATAN NAMA": "FUNGSIONAL",
        "JABATAN ID": "J0195",
        "JABATAN NAMA": "PERANCANG PERATURAN PERUNDANG-UNDANGAN AHLI PERTAMA",
        "TMT JABATAN": "2021-08-15",
        "TINGKAT PENDIDIKAN ID": "S3",
        "TINGKAT PENDIDIKAN NAMA": "DOKTOR",
        "PENDIDIKAN ID": "P1098",
        "PENDIDIKAN NAMA": "ILMU HUKUM",
        "TAHUN LULUS": 2020,
        "KPKN ID": "K018",
        "KPKN NAMA": "KPKN SURABAYA I",
        "LOKASI KERJA ID": "L3578",
        "LOKASI KERJA NAMA": "KANTOR WALIKOTA SURABAYA",
        "UNOR ID": "U9815",
        "UNOR NAMA": "SEKRETARIAT DAERAH - BAGIAN HUKUM DAN ORGANISASI",
        "INSTANSI INDUK ID": "I3500",
        "INSTANSI INDUK NAMA": "PEMERINTAH KOTA SURABAYA",
        "INSTANSI KERJA ID": "I3500",
        "INSTANSI KERJA NAMA": "PEMERINTAH KOTA SURABAYA",
        "SATUAN KERJA INDUK ID": "S091",
        "SATUAN KERJA INDUK NAMA": "SEKRETARIAT DAERAH",
        "SATUAN KERJA KERJA ID": "S099",
        "SATUAN KERJA KERJA NAMA": "SUB BAGIAN BANTUAN HUKUM",
        "IS VALID NIK": "YA",
        "NAMA SEKOLAH": "UNIVERSITAS AIRLANGGA",
        "FLAG IKD": "1",
        "GAJI": "",
        "NOMOR_KONTRAK": "SPK/4405/HUKUM/2021",
        "STATUS_PERPANJANGAN": "Belum Diproses"
    },
    {
        "PNS ID": "A827391823903",
        "NIP BARU": "199003052021022001",
        "NIP LAMA": "-",
        "NAMA": "BUDI SANTOSO",
        "GELAR DEPAN": "Ir.",
        "GELAR BELAKANG": "S.T.",
        "TEMPAT LAHIR ID": "3374",
        "TEMPAT LAHIR NAMA": "SEMARANG",
        "TANGGAL LAHIR": "1990-03-05",
        "JENIS KELAMIN": "L",
        "AGAMA ID": "1",
        "AGAMA NAMA": "ISLAM",
        "JENIS KAWIN ID": "1",
        "JENIS KAWIN NAMA": "KAWIN",
        "NIK": "3374020503900007",
        "NOMOR HP": "081322223333",
        "EMAIL": "budi.santoso@gmail.com",
        "EMAIL GOV": "budi.santoso@jatengprov.go.id",
        "ALAMAT": "Jl. Pandanaran No. 80, Semarang",
        "NPWP NOMOR": "48.223.334.4-012.000",
        "BPJS": "0003214567890",
        "JENIS PEGAWAI ID": "2",
        "JENIS PEGAWAI NAMA": "PPPK",
        "KEDUDUKAN HUKUM ID": "1",
        "KEDUDUKAN HUKUM NAMA": "AKTIF",
        "STATUS CPNS PNS": "PPPK",
        "KARTU ASN VIRTUAL": "ASN-V-19900305",
        "NOMOR SK CPNS": "800/012/PPPK/2021",
        "TANGGAL SK CPNS": "2021-02-01",
        "TMT CPNS": "2021-02-15", // Ended in Feb 2026 (Needs immediate attention!)
        "NOMOR SK PNS": "-",
        "TANGGAL SK PNS": "-",
        "TMT PNS": "-",
        "GOL AWAL ID": "IX",
        "GOL AWAL NAMA": "Golongan IX",
        "GOL AKHIR ID": "IX",
        "GOL AKHIR NAMA": "Golongan IX",
        "TMT GOLONGAN": "2021-02-15",
        "MK TAHUN": 5,
        "MK BULAN": 0,
        "JENIS JABATAN ID": "2",
        "JENIS JABATAN NAMA": "FUNGSIONAL",
        "JABATAN ID": "J0199",
        "JABATAN NAMA": "TEKNIK JALAN DAN JEMBATAN AHLI PERTAMA",
        "TMT JABATAN": "2021-02-15",
        "TINGKAT PENDIDIKAN ID": "S1",
        "TINGKAT PENDIDIKAN NAMA": "SARJANA",
        "PENDIDIKAN ID": "P1011",
        "PENDIDIKAN NAMA": "TEKNIK SIPIL",
        "TAHUN LULUS": 2013,
        "KPKN ID": "K020",
        "KPKN NAMA": "KPKN SEMARANG I",
        "LOKASI KERJA ID": "L3374",
        "LOKASI KERJA NAMA": "KANTOR DINAS PU JATENG",
        "UNOR ID": "U9820",
        "UNOR NAMA": "DINAS PEKERJAAN UMUM DAN BINA MARGA CIPTADA - UPTD WILAYAH SEMARANG",
        "INSTANSI INDUK ID": "I3300",
        "INSTANSI INDUK NAMA": "PEMERINTAH PROVINSI JAWA TENGAH",
        "INSTANSI KERJA ID": "I3300",
        "INSTANSI KERJA NAMA": "PEMERINTAH PROVINSI JAWA TENGAH",
        "SATUAN KERJA INDUK ID": "S091",
        "SATUAN KERJA INDUK NAMA": "DINAS PU",
        "SATUAN KERJA KERJA ID": "S092",
        "SATUAN KERJA KERJA NAMA": "UPTD WILAYAH SEMARANG",
        "IS VALID NIK": "YA",
        "NAMA SEKOLAH": "UNIVERSITAS DIPONEGORO",
        "FLAG IKD": "1",
        "GAJI": "",
        "NOMOR_KONTRAK": "SPK/0112/PU-JATENG/2021",
        "STATUS_PERPANJANGAN": "Belum Diproses"
    },
    {
        "PNS ID": "A827391823904",
        "NIP BARU": "198811122022032001",
        "NIP LAMA": "-",
        "NAMA": "RINA MARDIANA",
        "GELAR DEPAN": "Hj.",
        "GELAR BELAKANG": "S.Pd.",
        "TEMPAT LAHIR ID": "3273",
        "TEMPAT LAHIR NAMA": "BANDUNG",
        "TANGGAL LAHIR": "1988-11-12",
        "JENIS KELAMIN": "P",
        "AGAMA ID": "1",
        "AGAMA NAMA": "ISLAM",
        "JENIS KAWIN ID": "1",
        "JENIS KAWIN NAMA": "KAWIN",
        "NIK": "3273011112880004",
        "NOMOR HP": "081512341234",
        "EMAIL": "rina.mardiana@gmail.com",
        "EMAIL GOV": "rina.mardiana@jabarprov.go.id",
        "ALAMAT": "Jl. Setiabudhi No. 102, Bandung",
        "NPWP NOMOR": "48.334.445.5-012.000",
        "BPJS": "0006789123450",
        "JENIS PEGAWAI ID": "2",
        "JENIS PEGAWAI NAMA": "PPPK",
        "KEDUDUKAN HUKUM ID": "1",
        "KEDUDUKAN HUKUM NAMA": "AKTIF",
        "STATUS CPNS PNS": "PPPK",
        "KARTU ASN VIRTUAL": "ASN-V-19881112",
        "NOMOR SK CPNS": "800/314/PPPK/2022",
        "TANGGAL SK CPNS": "2022-03-01",
        "TMT CPNS": "2022-03-15", // Ends in March 2027 (Longer time)
        "NOMOR SK PNS": "-",
        "TANGGAL SK PNS": "-",
        "TMT PNS": "-",
        "GOL AWAL ID": "IX",
        "GOL AWAL NAMA": "Golongan IX",
        "GOL AKHIR ID": "IX",
        "GOL AKHIR NAMA": "Golongan IX",
        "TMT GOLONGAN": "2022-03-15",
        "MK TAHUN": 4,
        "MK BULAN": 3,
        "JENIS JABATAN ID": "2",
        "JENIS JABATAN NAMA": "FUNGSIONAL",
        "JABATAN ID": "J0201",
        "JABATAN NAMA": "GURU BAHASA INGGRIS AHLI PERTAMA",
        "TMT JABATAN": "2022-03-15",
        "TINGKAT PENDIDIKAN ID": "S1",
        "TINGKAT PENDIDIKAN NAMA": "SARJANA",
        "PENDIDIKAN ID": "P1122",
        "PENDIDIKAN NAMA": "PENDIDIKAN BAHASA INGGRIS",
        "TAHUN LULUS": 2011,
        "KPKN ID": "K025",
        "KPKN NAMA": "KPKN BANDUNG I",
        "LOKASI KERJA ID": "L3273",
        "LOKASI KERJA NAMA": "SMAN 1 BANDUNG",
        "UNOR ID": "U9830",
        "UNOR NAMA": "DINAS PENDIDIKAN PROVINSI JAWA BARAT - CABANG DINAS WILAYAH VII",
        "INSTANSI INDUK ID": "I3200",
        "INSTANSI INDUK NAMA": "PEMERINTAH PROVINSI JAWA BARAT",
        "INSTANSI KERJA ID": "I3200",
        "INSTANSI KERJA NAMA": "PEMERINTAH PROVINSI JAWA BARAT",
        "SATUAN KERJA INDUK ID": "S091",
        "SATUAN KERJA INDUK NAMA": "SEKRETARIAT DINAS PENDIDIKAN",
        "SATUAN KERJA KERJA ID": "S094",
        "SATUAN KERJA KERJA NAMA": "CABANG DINAS WILAYAH VII",
        "IS VALID NIK": "YA",
        "NAMA SEKOLAH": "UNIVERSITAS PENDIDIKAN INDONESIA",
        "FLAG IKD": "1",
        "GAJI": "",
        "NOMOR_KONTRAK": "SPK/0322/DIK-JABAR/2022",
        "STATUS_PERPANJANGAN": "Belum Diproses"
    }
];

// App State Management
let pppkData = [];
let extensionHistory = [];
let filteredData = [];
let selectedRows = new Set();
let selectedDueRows = new Set();
let currentPage = 1;
const rowsPerPage = 10;
let currentEditingItem = null;
let bulkMergeItems = null;
let dueBulkMergeItems = null;

// Template state variables
let tempTemplateF4Base64 = null;
let tempTemplateF4Name = "";
let tempTemplateF4Size = 0;

let tempTemplateA4Base64 = null;
let tempTemplateA4Name = "";
let tempTemplateA4Size = 0;

// The System Reference Date (from metadata 2026-06-25)
// The System Reference Date (from metadata 2026-06-25)
const systemDate = new Date("2026-06-25");
